name: job_portal
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  intl: ^0.16.1

  flutter:
    sdk: flutter
  datetime_picker_formfield: ^1.0.0

  dropdownfield: 1.0.3
  connectivity: ^0.4.6+2
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3
  shared_preferences: ^0.5.6
  cupertino_icons: ^0.1.3
  transformer_page_view: ^0.1.6
  splashscreen:
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/uu.png
    - images/uu1.png
    - images/uu2.png
    - images/uu3.png
    - login_logo.png
    - login_logo1.png
    - 123.png
    - logo3.jpg

    - 1.jpg
    - 2.jpg
    - 3.jpg
    - 4.png
    - Splashlog2.jpg
    - uu.png
    - uu1.png
    - uu2.png
    - uu3.png
    - rose.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fontss/Pacifico-Regular.ttf

    - family: Satisfy
      fonts:
        - asset: fontss/Satisfy-Regular.ttf